# Generated by Django 3.0.5 on 2024-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
